samanabrah/report/urls.py
from django.urls import path

from . import views


app_name = "report"

urlpatterns = [
    path("create/", views.ReportCreateView.as_view(), name="create"),
    # path("<int:pk>/", views.ReportDetailView.as_view(), name="detail"),
    # path(
    #     "<int:pk>/update/",
    #     views.ReportUpdateView.as_view(),
    #     name="update",
    # ),
    # path(
    #     "<int:pk>/delete/",
    #     views.ReportDeleteView.as_view(),
    #     name="delete",
    # ),
]

samanabrah/samanabrah/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_view

urlpatterns = [
    path("", users_view.user_login),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("report/", include("report.urls")),
]

samanabrah/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("reports/", views.reports, name="reports"),
]

samanabrah/report/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.shortcuts import reverse


class Report(models.Model):
    date = models.DateField(default=timezone.now)
    text = models.TextField()
    employee = models.ForeignKey(User, on_delete=models.PROTECT)

    def get_absolute_url(self):
        return reverse("users:report_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"Report of {self.employee.username.upper()} in date {self.date}"

samanabrah/report/forms.py
from django import forms

from .models import Report
from jalali_date.fields import JalaliDateField, SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ["date", "text"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["date"] = JalaliDateField(
            label="تاریخ",  # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget(
                attrs={
                    "placeholder": "تاریخ گزارش را انتخاب کنید",
                    "autocomplete": "off",
                }
            ),
        )
        self.fields["text"] = forms.CharField(
            label="متن گزارش",
            max_length=255,
            widget=forms.Textarea(
                attrs={
                    "placeholder": "متن گزارش را به صورت خلاصه و مفید بنویسید",
                    "rows": 5,
                    "class": "countdown",
                }
            ),
        )

samanabrah/report/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .forms import ReportForm
from .models import Report


# class ReportListView(ListView):
#     model = Report
#     template_name = "report/reports.html"
#     context_object_name = "reports"
#     ordering = ["-date"]


# class ReportDetailView(DetailView):
#     model = Report


class ReportCreateView(LoginRequiredMixin, CreateView):
    model = Report
    form_class = ReportForm
    template_name = "report/create.html"

    def form_valid(self, form):
        form.instance.employee = self.request.user
        return super().form_valid(form)


# class ReportUpdateView(LoginRequiredMixin, UpdateView):
#     model = Report
#     form_class = ReportForm
#     template_name = "report/update.html"

#     def form_valid(self, form):
#         form.instance.employee = self.request.user
#         return super().form_valid(form)


# class ReportDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
#     model = Report
#     success_url = "/report"

#     def test_func(self):
#         Report = self.get_object()
#         if self.request.user == Report.employee:
#             return True
#         return False

samanabrah/users/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from report.models import Report


def reports(request):
    reports = Report.objects.filter(employee=request.user)
    return render(request, "users/reports.html", {"reports": reports})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("users:reports")
        else:
            messages.error(request, "نام کاربری یا رمز ورود اشتباه است.")
    # If users is already logged in go to main page
    if request.user.is_authenticated:
        return redirect("users:reports")
    return render(request, "users/login.html")


def user_logout(request):
    logout(request)
    return redirect("users:login")

samanabrah/report/templates/report/create.html
{% extends "base.html" %}

{% load static %}
{% load jalali_tags %}


{% block title %}گزارش{% endblock title %}
{% block style %}
<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
{% endblock style %}

{% block main %}
<div class="container">
  <h1>ایجاد گزارش جدید</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit"value="ایجاد گزارش">
  </form>
</div>
{% endblock main %}

{% block script %}
<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
<script src="{% static 'users/js/vcount.js' %}"></script>
<script>
  VCountdown({
    target: '.countdown',
    maxChars: "{{ form.fields.text.max_length }}",
  });
</script>
{% endblock script %}

samanabrah/report/templates/report/reports.html
{% extends 'base.html' %}
{% block main %}
{% for report in reports %}
    <p>{{ report.text }}</p>
{% endfor %}
{% endblock main %}

samanabrah/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block style %}{% endblock style %}
    <title>{% block title %}{% endblock title%}</title>
</head>
<body>
  <header>
    {% include 'includes/navbar.html' %}
    {% include 'includes/messages.html' %}
  </header>
  <main>
    {% block main %}{% endblock main %}
  </main>
  <footer><p>کلیه حقوق مادی معنوی این وب سایت متعلق به شرکت سامان آبراه می باشد.</p></footer>
  <!-- Script for specific page -->
  {% block script %}
  {% endblock script %}
</body>
</html>

samanabrah/templates/includes/messages.html
{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

samanabrah/templates/includes/navbar.html
<nav class="main-nav">
  <ul>
    {% if user.is_authenticated %}
      <li><a href="{% url 'report:create' %}">افزودن گزاش</a></li>
      <li><a href="{% url 'users:logout' %}">خروج</a></li>
    {% endif %}
  </ul>
</nav>

samanabrah/users/templates/users/dashboard.html
{% extends 'base.html' %}
{% block title %}داشبورد{% endblock title %}
{% block main %}
<div class="container dashboard">
  {% for report in reports %}
    <ul class="row">
      <li>{{ report.date }}</li>
      <li>{{ report.text|truncatechars:150 }}</li>
      <input class="edit" type="button" value="ویرایش">
      <input class="error" type="button" value="حذف">
    </ul>
  {% endfor %}
</div>
{% endblock main %}

samanabrah/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock title %}
{% block main %}
<div class="container login">
  <div class="right">
    <img src="{% static 'img/right.jpg' %}" alt="water image">
  </div>
  <form action="{% url 'users:login' %}" method="POST">
    <h1>ورود کارمندان</h1>
    {% csrf_token %}
    <input class="entry" type="text" name="username" id="username_id" placeholder="نام کاربری">
    <input class="entry" type="password" name="password" id="password_id" placeholder="رمز ورود">
    <input class="btn" type="submit" value="ورود">
  </form>
</div>
{% endblock main %}